name: dartemis_transformer
version: 0.1.0
author: Dennis Kaselow <Dennis.Kaselow+dartemis@gmail.com>
description: A transformer to modify and generate code that turns Components into PooledComponents and initializes EntitySystems and Managers.
homepage: https://github.com/denniskaselow/dartemis
environment:
  sdk: '>=1.8.0 <2.0.0'
dependencies:
  analyzer: ^0.24.0
  barback: ^0.15.2
  dart_style: ^0.1.7
  dartemis: ^0.7.0
dev_dependencies:
  unittest: ^0.11.5
  mockito: ^0.8.2
